linters:
  disable-all: true
  enable:
    - govet
    - gofmt
    - unused
    - ineffassign 
    - staticcheck

issues:
  exclude-dirs:
    - vendor
    - migrations
    - migrate
  exclude-files:
    - .*_test\.go
