APP_NAME: catalog-service
APP_ENV: dev
PORT: 4000
SOME_INT_KEY: 42
LOG_LEVEL: DEBUG
OPENSEARCH_HOST_SERVERS: http://localhost:9200
OPENSEARCH_MAX_IDLE_CONNS: 100
OPENSEARCH_MAX_IDLE_CONNS_PER_HOST: 100
OPENSEARCH_IDLE_CONN_TIMEOUT_MS: 90000
OPENSEARCH_DIAL_TIMEOUT_MS: 30000
OPENSEARCH_KEEP_ALIVE_MS: 30000
OPENSEARCH_TLS_HANDSHAKE_TIMEOUT_MS: 10000
